/**
 * Application-level Order Status Types
 * These are completely separate from database transitions
 */

export enum OrderStatus {
  NEW = 'NEW',
  IN_PROGRESS = 'IN_PROGRESS', 
  READY_FOR_DISPATCH = 'READY_FOR_DISPATCH',
  DISPATCH_INITIATED = 'DISPATCH_INITIATED',
  DISPATCH_PARTNER_BOOKED = 'DISPATCH_PARTNER_BOOKED'
}

export enum OrderTransitionStatus {
  ORDER_INITIATED = 'ORDER_INITIATED',
  TASK_ASSIGNMENT = 'TASK_ASSIGNMENT',
  TASK_COMPLETION = 'TASK_COMPLETION',
  TASK_APPROVED = 'TASK_APPROVED',
  TASK_REJECTED = 'TASK_REJECTED',
  READY_FOR_DISPATCH = 'READY_FOR_DISPATCH',
  DISPATCH_INITIATED = 'DISPATCH_INITIATED',
  DISPATCH_PARTNER_BOOKED = 'DISPATCH_PARTNER_BOOKED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED'
}
